### PR TITLE
iOS + Android file serving support

### PR DESCRIPTION
**Pull request by boedy**
@bykof Thanks for your work thus-far. Next to adding on-par functionality I made some changes in the setup.

This PR accomplishes: 

- [x] Include GCDWebServer as Pod
- [x] iOS and Android file serving
- [x] Mandatory mime type param made optional. Mime type guessed based on file extension.
- [x] Keep server running in background by default
- [x] Raise error if webserver is already running
- [x] Addresses: https://github.com/bykof/cordova-plugin-webserver/issues/28

Todo (upcoming PR's):
- [ ] Include NanoHttpD as Gradle dependency
- [ ] Method to return IP address of webserver where it can be reached on

### CODE REVIEW

**Comment by bykof** [comment]
@boedy thank you very much for your Pull Request. I am honestly so busy right now, that I cannot maintain the project seriously, so I am really happy that there are guys like you!

I read through your pull requests and it looks pretty good. I will merge it and make you also a maintainer, so you can just push to the project.

**Comment by boedy** [comment]
Gotcha. I originally did not intend to help maintain the project, but I might as well as we'll be using this plugin in production. I'll see what I can do.

**Comment by bykof** [comment]
Could you tell me for what purpose you use this plugin in the application?

**Comment by boedy** [comment]
We use it to facilitate communications between a media device (i.e. smartspeaker) running on the local network and our app. We thereby respond to http request serving both media files and JSON responses.

**Comment by digaus** [comment]
@boedy 

Any progress on "Method to return IP address of webserver where it can be reached on"?

Currently using Cordova Httpd plugin to serve zip files for ota updates of smarthome devices. For that I need to tell them the URL/IP which they need to pull the zip files from.

Maybe you can check here: https://github.com/floatinghotpot/cordova-httpd

**Comment by boedy** [comment]
@digaus Sorry have not yet had any time to work on this. [I have a working branch where this already implemented](https://github.com/boedy/cordova-plugin-webserver/tree/get-ip). You can maybe use that for the time being.

The reason I'm waiting with a PR, is because I would like to get the versioning of this package strait first.

**Comment by digaus** [comment]
> @digaus Sorry have not yet had any time to work on this. [I have a working branch where this already implemented](https://github.com/boedy/cordova-plugin-webserver/tree/get-ip). You can maybe use that for the time being.
> 
> The reason I'm waiting with a PR, is because I would like to get the versioning of this package strait first.

No problem, I currently use WifiWizzard2 which gives me the option to get the IP. Also have an issue open for Ionic Native for other bugs there: https://github.com/ionic-team/ionic-native/issues/3126

**Pull request merged**
